name: Python application

on:
  pull_request:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.DOCKER_HUB_PW }}" | docker login -u "imenazizov" --password-stdin
        docker image build -t imenazizov/gitops:hellov1.0 .
        docker push imenazizov/gitops:hellov1.0
